# Generated by Django 2.2 on 2021-12-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Почта автора')),
                ('post_text', models.TextField(max_length=3000, verbose_name='Текст записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.TextField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=100, verbose_name='Статус')),
            ],
        ),
    ]
